<template>
  <el-option label="全部" value="" />
  <el-option label="IC" value="IC" />
  <el-option label="5A" value="5A" />
  <el-option label="钽电容" value="钽电容" />
  <el-option label="电解电容" value="电解电容" />
  <el-option label="接口" value="接口" />
  <el-option label="PNP" value="PNP" />
  <el-option label="晶振" value="晶振" />
  <el-option label="1117" value="1117" />
  <el-option label="CAP" value="CAP" />
  <el-option label="FET" value="FET" />
  <el-option label="IND" value="IND" />
  <el-option label="LED" value="LED" />
  <el-option label="MOS管" value="MOS管" />
  <el-option label="NPN" value="NPN" />
  <el-option label="PNP" value="PNP" />
  <el-option label="RES" value="RES" />
  <el-option label="SNAP MAKER" value="SNAP MAKER" />
  <el-option label="TF卡座" value="TF卡座" />
  <el-option label="USB" value="USB" />
  <el-option label="XTAL" value="XTAL" />
  <el-option label="按钮" value="按钮" />
  <el-option label="保险丝" value="保险丝" />
  <el-option label="插头" value="插头" />
  <el-option label="插座" value="插座" />
  <el-option label="传感器" value="传感器" />
  <el-option label="串口通信模块" value="串口通信模块" />
  <el-option label="磁铁" value="磁铁" />
  <el-option label="磁珠" value="磁珠" />
  <el-option label="底座" value="底座" />
  <el-option label="电感" value="电感" />
  <el-option label="电机" value="电机" />
  <el-option label="电容" value="电容" />
  <el-option label="电位器" value="电位器" />
  <el-option label="电阻" value="电阻" />
  <el-option label="垫圈" value="垫圈" />
  <el-option label="顶针" value="顶针" />
  <el-option label="端子" value="端子" />
  <el-option label="舵机" value="舵机" />
  <el-option label="耳机插座" value="耳机插座" />
  <el-option label="二极管" value="二极管" />
  <el-option label="干电池" value="干电池" />
  <el-option label="基本元器件" value="基本元器件" />
  <el-option label="继电器" value="继电器" />
  <el-option label="接口" value="接口" />
  <el-option label="接头" value="接头" />
  <el-option label="接线柱" value="接线柱" />
  <el-option label="镜头" value="镜头" />
  <el-option label="卡座" value="卡座" />
  <el-option label="开关" value="开关" />
  <el-option label="密封圈" value="密封圈" />
  <el-option label="模块" value="模块" />
  <el-option label="排母" value="排母" />
  <el-option label="排针" value="排针" />
  <el-option label="三极管" value="三极管" />
  <el-option label="摄像头" value="摄像头" />
  <el-option label="弯折铝管" value="弯折铝管" />
  <el-option label="无线仿真器" value="无线仿真器" />
  <el-option label="扬声器" value="扬声器" />
  <el-option label="语音合成模块" value="语音合成模块" />
  <el-option label="直插式电解电容" value="直插式电解电容" />
  <el-option label="直插式铝电解电容" value="直插式铝电解电容" />
  <el-option label="钻头" value="钻头" />
</template>
